import { ReactNode } from 'react'

import { pretendardFont } from 'src/styles'

import type { Metadata } from 'next'

import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Resume',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={pretendardFont.className}>{children}</body>
    </html>
  )
}
